USE mydb5;
drop TABLE Member;

CREATE TABLE Member (
	id VARCHAR(20) PRIMARY KEY, 
    password VARCHAR(50) NOT NULL,
    email VARCHAR(20) NOT NULL UNIQUE,
    nickName VARCHAR(20) NOT NULL UNIQUE,
    inserted DATETIME NOT NULL DEFAULT NOW()
);
ALTER TABLE Member MODIFY COLUMN email  VARCHAR(50) NOT NULL UNIQUE;

ALTER TABLE Member MODIFY COLUMN password  VARCHAR(100) NOT NULL;
DESC Member;
SELECT * FROM Member;
